<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MK78P6P" failures="1" tests="6" name="TestNG.TestNG_Assertions" time="0.027" errors="0" timestamp="2023-06-05T14:35:17 IST" skipped="5">
  <testcase classname="TestNG.TestNG_Assertions" name="TC6" time="0.027">
    <failure message="Result is not Null expected [null] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result is not Null expected [null] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotSame(Assert.java:1033)
at org.testng.Assert.assertNull(Assert.java:965)
at TestNG.TestNG_Assertions.TC6(TestNG_Assertions.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC6 -->
  <system-out>
    <![CDATA[Running TC6]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="TC5">
    <skipped/>
  </testcase> <!-- TC5 -->
  <system-out/>
  <testcase classname="TestNG.TestNG_Assertions" name="TC2">
    <skipped/>
  </testcase> <!-- TC2 -->
  <system-out/>
  <testcase classname="TestNG.TestNG_Assertions" name="TC4">
    <skipped/>
  </testcase> <!-- TC4 -->
  <system-out/>
  <testcase classname="TestNG.TestNG_Assertions" name="TC3">
    <skipped/>
  </testcase> <!-- TC3 -->
  <system-out/>
  <testcase classname="TestNG.TestNG_Assertions" name="TC1">
    <skipped/>
  </testcase> <!-- TC1 -->
  <system-out/>
</testsuite> <!-- TestNG.TestNG_Assertions -->
